MODULES = repeatbench
EXTENSION = repeatbench
DATA = repeatbench--1.0.sql
PGFILEDESC = "repeatbench - verify repeat() copy strategies"

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)